version: '3.5'
services:

  influxdb:
    container_name: jmeter-influxdb
    image: influxdb:alpine
    environment:
      INFLUXDB_DB: jmeter_results
    ports:
     - "8086:8086"
    networks:
     - jmeter-network

  grafana:
    container_name: jmeter-grafana
    image: grafana/grafana:latest
    depends_on:
      - influxdb
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - "3000:3000"
    env_file:
      - 'grafana.env'
    links:
      - influxdb
    networks:
      - jmeter-network

networks:
  jmeter-network:
    driver: bridge
